if @project.errors.any?
  flash.now["projectFormErrors"] = @project.errors.as_json
end

json.project do
  json.name @project.name
  json.images @project.images.map { |image| { id: image.id, url: url_for(image) } }
end

json.projectForm(partial: 'form') do
end

json.projectPath project_path(@project)
json.projectsPath projects_path
