json.projects do
  json.array! @projects do |project|
    json.id project.id
    json.user_id project.user_id
    json.name project.name
    json.description project.description
    json.images project.images.map { |image| url_for(image) }
    json.is_public project.is_public
    json.created_at project.created_at
    json.updated_at project.updated_at
    json.editProjectPath edit_project_path(project)
    json.projectPath project_path(project)
    json.deleteForm do
      form_props(model: project, method: :delete)
    end
  end
end

json.newProjectPath new_project_path
